version: '3.9'
services:
  ssh.cyrhades.fr:
    build: ./.docker/ssh
    labels:
      ho.ctf.cyrhades: "1"
  webssh.cyrhades.fr:
    build: ./.docker/webssh
    ports:
      - ${PORT}:8888
    environment:
      - HOOS_CTF_USERNAME=${HOOS_CTF_USERNAME:-}
    labels:
      ho.ctf.cyrhades: "1"
  xoring-networks-baby.cyrhades.fr:
    image: anssi/fcsc2020-misc-xoring-networks-baby:latest
    ports:
      - "4000:4000"
    labels:
      ho.ctf.cyrhades: "1"
