version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
      - "80:8888"
  xoring-networks-baby.cyrhades.com:
    image: anssi/fcsc2020-misc-xoring-networks-baby:latest
    ports:
      - "4000:4000"